<a href="https://colab.research.google.com/github/cbg27/NLP_Final/blob/main/Baseline/NLP_DATA_CLEANUP_train_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import pandas as pd
from bs4 import BeautifulSoup
from google.colab import drive
import os
import joblib as jp
import pickle
import re 
from tqdm import tqdm, tqdm_notebook
tqdm_notebook().pandas()
from sklearn.feature_extraction.text import TfidfVectorizer

<ipython-input-1-1c78345eef4c>:14: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  tqdm_notebook().pandas()


0it [00:00, ?it/s]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

data_prep_path= '/content/drive/MyDrive/dataPrep/code/'
data_prep_path_final='/content/drive/MyDrive/dataPrepFinal/code/'

Mounted at /content/drive


In [ ]:
df_so_2 = pd.read_pickle(f"{data_prep_path}/df_so_2.pkl")

In [ ]:
df_so_2 = df_so_2.head(20000)

In [ ]:
def dummy_tokenizer(string): return string

# we will only get the 10,000 most common words for title to limit size of dataset
title_vectorizer = TfidfVectorizer(tokenizer=dummy_tokenizer, lowercase=False, max_features=10000)
x_title = title_vectorizer.fit_transform(df_so_2["title_tokenized"])

In [ ]:
x_title

<20000x10000 sparse matrix of type '<class 'numpy.float64'>'
	with 99724 stored elements in Compressed Sparse Row format>

In [ ]:
body_vectorizer = TfidfVectorizer(tokenizer=dummy_tokenizer, lowercase=False, max_features=100000)
x_body = body_vectorizer.fit_transform(df_so_2["body_tokenized"])

In [ ]:
x_title = x_title * 2

In [ ]:
from scipy.sparse import hstack
from sklearn.model_selection import train_test_split

X = hstack([x_title, x_body])
y = df_so_2[["tags"]]
print(y)

                                               tags
0                       [flex, actionscript-3, air]
1                                             [svn]
2                                    [sql, asp.net]
3            [algorithm, language-agnostic, colors]
4      [c#, .net, scripting, compiler-construction]
...                                             ...
20806                        [python, proxy, https]
20807                                  [javascript]
20808                          [javascript, jquery]
20809                    [website, save, scripting]
20810                     [c++, winapi, x86, 64bit]

[20000 rows x 1 columns]


In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

multi_label_binarizer = MultiLabelBinarizer()
y = multi_label_binarizer.fit_transform(y["tags"])

In [ ]:
print(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
import joblib
joblib.dump(X_train, f"{data_prep_path_final}/x_train.pkl")
joblib.dump(X_test, f"{data_prep_path_final}/x_test.pkl")
joblib.dump(y_train, f"{data_prep_path_final}/y_train.pkl")
joblib.dump(y_test, f"{data_prep_path_final}/y_test.pkl")
joblib.dump(multi_label_binarizer.classes_, f"{data_prep_path_final}/y_classes.pkl")

['/content/drive/MyDrive/dataPrepFinal/code//y_classes.pkl']